---
title: "Activities"
---

## IDA glossary

### **Project description**

The objective is to provide definitions of common terms used by the Initial Data Analysis topics group. Every effort will be made to use existing opne access definitions.

Authors: All TG3 members

Project status: **NEW**

### **Project outcomes:**

Glossary of 10-15 terms with definitions, e.g IDA, EDA, data cleaningm data screening, data quality, 


## Incorporating IDA in courses on statistics

### **Project description**

The objective is to provide an engaging application using characters from the Pokémon franchise, using a multivariable linear regression model to address the research question aimed at evaluating the association between Pokémon species weight and other characteristics.

Lead: Lara Lusa

Project status: **ACTIVE**

### **Project outcomes:**

1.\ Manuscript for a journal with a "Teaching corner"

2.\ Curated Pokemon data set for open access

3.\ R code for initial data analysis and for regression models

4.\ Statistical analysi plan for the hypothetical research question for analyzing the Pokemon data




## IDA for regression models

### **Project description**

The objective is to provide examples on conducting initial data analysis (IDA) in a reproducible manner in the context of intended regression analyses.

Authors: Georg Heinze, Mark Baillie, Lara Lusa, Carsten O Schmidt, Willi Sauerbrei, Frank E Harrell, Marianne Huebner

This is a joint project between the Topic Groups 2 and 3 of the STRATOS Initiative.

Project status: **ACTIVE, paper submitted**

### **Project outcomes:**

1.  Open access dataset: [bacteremia](https://zenodo.org/records/7554815)

2.  [IDA report with R code](https://stratosida.github.io/regression-regrets/)

3.  IDA plan (check list) for the example(s)

4.  Manuscript with scope of regression model, results, and consequences of IDA for regression

5.  [Preprint](https://assets.researchsquare.com/files/rs-3580334/v1/b6c6d5fd-9a7e-4e81-a06e-9e647a52caf7.pdf)


## IDA for longitudinal data

### **Project description**

The objective is to provide an example of initial data anlysis for longitudinal data.

Authors: Lara Lusa, Cecile Proust-Lima, Katherine Lee, Frank Lawrence, Carsten Schmidt, Mark Baillie, Saskia le Cessie, Marianne Huebner

Project status: **CLOSED, paper published**

### **Project outcomes:**

1.\  IDA plan [check list](assets/IDAchecklist_long.pdf)

2.\  [IDA report with R code](https://stratosida.github.io/longitudinal/)

3.\  Manuscript with IDA workflow in the example of the SHARE data:

Lusa L, Proust-Lima C, Schmidt CO, Lee KJ, le Cessie S, Baillie M, Lawrence F, Huebner M; TG3 of the STRATOS Initiative. Initial data analysis for longitudinal studies to build a solid foundation for reproducible analysis. PLoS One. 2024 May 29;19(5):e0295726. [doi: 10.1371/journal.pone.0295726](https://doi.org/10.1371/journal.pone.0295726)


### **Supplementary material**

The Survey of Health Ageing and Retirement in Europe (SHARE) consists of data on health and socioeconomic variables of non-institutionalized individuals aged 50 and older across several European countries. The data sets includes about 140 000 men and women, ages 50 or older, collected in years 2004 to 2018. The questionnaires include questions on demographics, health (physical, and mental health, cognitive function, grip strength and behavioral risks), and socio-economic status. <https://share-eric.eu>

**Open Science Framework: R code**

Lusa L, Huebner M. (2021, September 17). Repository with R vignettes to support data organization and analysis for the SHARE study. <https://doi.org/10.17605/OSF.IO/KGTX6>

## Systematic review of IDA reporting

### **Project description**

Our aim was to describe the practice of reporting of initial data analyses in observational studies in five highly ranked medical journals with focus on data cleaning, screening, and reporting of findings which led to a potential change in the analysis plan.

Authors: Marianne Huebner, Werner Vach, Saskia le Cessie, Carsten Oliver Schmidt, Lara Lusa

Project status: **CLOSED, paper published**

### **Project outcomes**

1\. Summary of current IDA reporting by location in papers with examples.

2\. Recommendations for reporting practice of IDA in papers

3\. Manuscript:

Hidden analyses: a review of reporting practice and recommendations for more transparent reporting of initial data analyses

BMC Med Res Meth (2020) 20:61. <https://doi.org/10.1186/s12874-020-00942-y>

### **Supplementary material**

In the [assets](https://github.com/stratosida/stratosida.github.io/tree/main/assets/) folder 

1\. Study protocol for IDA literature review: [Protocol_IDA20180620.pdf](assets/Protocol_IDA20180620.pdf)

2\. Design of IDA collection form: [Collection_Form_20181129.pdf](assets/Collection_Form_20181129.pdf)
