---
title: "Glossary"
---

### Initial Data Analysis

The main aim of IDA is seen in providing reliable knowledge about the data to enable responsible statistical analyses and interpretation. 
IDA has the following phases: (1) metadata setup; (2) data cleaning; (3) data screening; (4) initial data reporting; 
(5) refining and updating the research analysis plan; and (6) documenting and reporting IDA. IDA is aligned with the research aims 
and the statistical analysis plan and does not include hypothesis generating activities.  
 
**Source:** Schmidt CO, Vach W, le Cessie S, Huebner M. STRATOS: Introducing the Initial Data Analysis Topic Group (TG3). Biometric Bulletin 2018; 35 (2): 10-11

[Link](https://www.stratos-initiative.org/sites/default/files/2021-11/STRATOS-TG3-BB-initial-data-analysis.pdf) 


### Exploratory Data Analysis

Exploratory Data Analysis (EDA) inspects data to uncover patterns in the data or identifies possible errors and anomalies, for example through graphical approaches. EDA may include investigations for model building and hypothesis generation in a cyclical manner.  
 
**Source:** Lusa L, Proust-Lima C, Schmidt CO, Lee KJ, le Cessie S, Baillie M, Lawrence F, Huebner M; TG3 of the STRATOS Initiative. Initial data analysis for longitudinal studies to build a solid foundation for reproducible analysis. PLoS One. 2024 May 29;19(5):e0295726. doi: 10.1371/journal.pone.0295726.

[Link](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0295726) 

**References:**

Behrens JT. Principles and procedures of exploratory data analysis. Psychological methods. 1997;2(2):131. <https://core.ac.uk/download/pdf/193648223.pdf>

Cook D, Swayne DF. Interactive and Dynamic Graphics for Data Analysis: With R and Ggobi. New York, NY: Springer New York; 2007. <https://en.wikipedia.org/wiki/Exploratory_data_analysis> 


### Statistical Analysis Plan (SAP)

A statistical analysis plan is a document that contains a more technical and detailed elaboration of the principal features of the analysis described in the protocol and includes detailed procedures for executing the statistical analysis of the primary and secondary variables and other data.  

**Source:** International Council for Harmonisation (ICH E9). ICH: E 9: Statistical principles for clinical trials - Step 5. Glossary p. 37 

[Link](https://www.ema.europa.eu/en/ich-e9-statistical-principles-clinical-trials-scientific-guideline)  


### Data wrangling

Data Wrangling is a broad term referring to the processes involved when preparing data for analysis. It can include acquiring data, enriching, changing the format and shape of the data, combining, subsetting and sampling data, and cleaning data. Some common steps involved with Data Wrangling are: 

* Discovering and gathering the data needed 
* Merging data from different sources, if necessary  
* Fixing flaws in the data entries  
* Extracting the necessary data and put it in the proper structure  
* Storing it in the proper format for further use 

**Source:** National Library of Medicine

[Link](https://www.nnlm.gov/guides/data-glossary/data-wrangling) 


