---
title: "R implementations"
---

### IDA report for regression models

[Bacteremia data set](https://zenodo.org/records/7554815) by Georg Heinze

<https://stratosida.github.io/regression-regrets/>

This example is also discussed with R code by Frank Harrell in Regression Modelling Strategies:
<https://hbiostat.org/rmsc/bacteremia>

### IDA report for longitudinal studies

Grip strength data set from the [SHARE project](https://share-eric.eu)

<https://stratosida.github.io/longitudinal/>

### Teaching a workflow for regression analyses: Pokémon case study

*1.\ Pokémon data*

-  Curated [Data tsv](assets/Pokemon_clean.tsv)

-  Pokémon R data set after IDA [Rdata](assets/Pokemon_afterIDA.Rdata)

-  Pokémon data dictionary [Dictionary xlsx](assets/Pokemon_datadictionary.xlsx)

*2.\ Statistical analysis plan (SAP)*

- [SAP version 1](assets/SAP_v1_Pokemon.docx)

- [SAP version 2 - updated after IDA](assets/SAP_v2_Pokemon.docx)

*3.\ Initial data analysis (IDA) report* 

- [IDA report -- html](https://stratosida.github.io/case_pokemon/Pokemon_IDA_main.html)

- [IDA report -- R markdown (download)](https://stratosida.github.io/case_pokemon/Pokemon_IDA_main.Rmd)

- [Additional IDA  -- html](https://stratosida.github.io/case_pokemon/Pokemon_IDA_additional.html)

- [Additional IDA -- R markdown (download)](https://stratosida.github.io/case_pokemon/Pokemon_IDA_additional.Rmd)


*4.\  Regression analysis report -main data analysis (MDA)*

- [MDA report -- html](https://stratosida.github.io/case_pokemon/Pokemon_regression_main.html)

- [MDA report -- R markdown (download)](https://stratosida.github.io/case_pokemon/Pokemon_regression_main.Rmd)

- [Additional MDA -- html](https://stratosida.github.io/case_pokemon/Pokemon_regression_additional.html)

- [Additional MDA -- R markdown (download)](https://stratosida.github.io/case_pokemon/Pokemon_regression_additional.Rmd)


