---
title: "SAPI Statement"
---

### Background

The Statistical Analysis Plan for observational studies with an Initial data analysis plan (SAPI) statement consists of a 27-item checklist and an expanded checklist that details recommendations for each item.

SAPI guides researchers and analysts in the development of a statistical analysis plan for observational studies that incorporates a systematic process for initial data analysis. It can be used to develop analysis plans for many types of research objectives.

SAPI promotes transparency, reproducibility, integrity, and interpretability of analysis results.

The SAPI statement was developed via an international consensus process.


### Key documents

SAPI expanded checklist: [Word](assets/SAPI_checklist_final.docx) or [HTML](sapi.qmd)

SAPI paper (under review)

SAPI Explanation and Elaboration (in progress)



### Examples of statistical analysis plans [Links to be added]

Longitudinal study to estimate grip strength (SHARE): SAP v1, SAP v2

Cross-sectional study to predict bacteremia status ([data](https://zenodo.org/records/7554815)): SAP v1, SAP v2

Longitudinal study to estimate learning curves (VQI registry): [SAP in Supplement](https://academic.oup.com/jsprm/article/doi/10.1093/jsprm/snag006/8748610)


### Translations

-- German in progress--


### Reporting guidelines for different types of studies

[EQUATOR Network](https://www.equator-network.org)

### Contact
