project:
  type: site
  output-dir: _site


execute:
  freeze: true

site:
  title: "STRATOS TG3: Initial Data Analysis"
  
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/stratosida/
    contents:
      - index.qmd
      - members.qmd
      - papers.qmd
      - activities.qmd
      - resources.qmd
    logo: "images/stratos-color-transpbackgr.png"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

